# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - cargo check

builds:
  - id: "timedctl"
    builder: "rust"
    binary: "timedctl"
    targets:
      - "x86_64-unknown-linux-gnu"
      - "x86_64-apple-darwin"
      - "x86_64-pc-windows-msvc"
    tool: "cross"
    command: "build"
    flags:
      - "--release"
    skip: false

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Performance Improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: cfi2017
    name: timedctl-rs
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
