name: Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.semantic.outputs.released }}
      version: ${{ steps.semantic.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install go-semantic-release
        run: go install github.com/go-semantic-release/semantic-release/v2@latest

      - name: Install cargo-bump
        run: cargo install cargo-bump

      - name: Build release
        run: cargo build --release

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release -vf
          echo "released=${{ steps.semantic.outputs.released }}" >> $GITHUB_OUTPUT
          echo "version=${{ steps.semantic.outputs.version }}" >> $GITHUB_OUTPUT

  build-and-upload:
    name: Build and Upload Release Assets
    needs: release
    if: needs.release.outputs.released == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: timedctl
            asset_name: timedctl-linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: timedctl
            asset_name: timedctl-linux-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: timedctl
            asset_name: timedctl-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: timedctl
            asset_name: timedctl-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: timedctl.exe
            asset_name: timedctl-windows-amd64.exe

    steps:
      - uses: actions/checkout@v3
        with:
          ref: v${{ needs.release.outputs.version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Release Asset
        uses: go-semantic-release/upload-assets-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          name: ${{ matrix.asset_name }}
